
spring.application.name=payment-service

stripe.secretKey=sk_test_51SD1lZDdDSVipXYCUTDIGJpKmNjMMrHW3ag9pUGLLY462STpT13gDsOdQRDoHmORtGcoHuroKUVDatIepVH5TANd00zMcDJZBL
stripe.webhookSecret=whsec_8fb0ae50bff7e439947094edb22a88a0bb9666e0fb0e926c507b77b2525a4448

stripe.success-url=http://localhost:8080/success
stripe.cancel-url=http://localhost:8080/cancel
stripe.default-currency=USD

spring.output.ansi.enabled=ALWAYS

    # JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=denizpostgre1928
spring.datasource.driver-class-name=org.postgresql.Driver

stripe listen --forward-to localhost:8080/webhook